export const subnetDataList = [
  { key: "tempo", label: "Tempo" },
  { key: "minAllowedWeights", label: "Min Allowed Weights" },
  { key: "maxAllowedWeights", label: "Max Allowed Weights" },
  { key: "maxAllowedUids", label: "Max Allowed UIDs" },
  { key: "maxWeightAge", label: "Max Weight Age" },
  { key: "trustRatio", label: "Trust Ratio" },
  { key: "founderShare", label: "Founder Share" },
  { key: "incentiveRatio", label: "Incentive Ratio" },
  { key: "maximumSetWeightCallsPerEpoch", label: "Max Set Weight Calls" },
  { key: "bondsMa", label: "Bonds MA" },
  { key: "immunityPeriod", label: "Immunity Period" },
  { key: "proposalCost", label: "Proposal Cost" },
  { key: "proposalExpiration", label: "Proposal Expiration" },
  { key: "voteMode", label: "Vote Mode" },
  {
    key: "proposalRewardTreasuryAllocation",
    label: "Proposal Reward Treasury Allocation",
  },
  {
    key: "maxProposalRewardTreasuryAllocation",
    label: "Max Proposal Reward Treasury Allocation",
  },
  { key: "proposalRewardInterval", label: "Proposal Reward Interval" },
  { key: "minBurn", label: "Min Burn" },
  { key: "maxBurn", label: "Max Burn" },
  { key: "adjustmentAlpha", label: "Adjustment Alpha" },
  {
    key: "targetRegistrationsInterval",
    label: "Target Registrations Interval",
  },
  {
    key: "targetRegistrationsPerInterval",
    label: "Target Registrations Per Interval",
  },
  {
    key: "maxRegistrationsPerInterval",
    label: "Max Registrations Per Interval",
  },
  { key: "minValidatorStake", label: "Min Validator Stake" },
  { key: "maxAllowedValidators", label: "Max Allowed Validators" },
];
